INSERT INTO LIST_ENTITY (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'To Do', 0);

INSERT INTO LIST_ENTITY (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Doing', 1);

INSERT INTO LIST_ENTITY (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Done', 2);

INSERT INTO LIST_ENTITY (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'To Think', 3);



INSERT INTO ITEM (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION,LIST_ID)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Cook', 0, 1);

INSERT INTO ITEM (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION,LIST_ID)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Run', 1, 1);

INSERT INTO ITEM (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION,LIST_ID)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Write', 0, 2);

INSERT INTO ITEM (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION,LIST_ID)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Research', 0, 3);

INSERT INTO ITEM (CREATED_ON, DELETED,MODIFIED_ON,NAME,POSITION,LIST_ID)
VALUES (CURRENT_TIMESTAMP, false, CURRENT_TIMESTAMP, 'Vacation', 0, 4);

