CREATE TABLE LIST_ENTITY (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CREATED_ON datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED tinyint(1) DEFAULT 0,
  MODIFIED_ON datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  NAME varchar(255) DEFAULT NULL,
  POSITION int DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ITEM (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CREATED_ON datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELETED tinyint(1) DEFAULT 0,
  MODIFIED_ON datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  NAME varchar(255) DEFAULT NULL,
  LIST_ID bigint(20) NOT NULL,
  POSITION int DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_LIST_ID_ITEM FOREIGN KEY (LIST_ID) REFERENCES LIST_ENTITY (ID)
);
